-- Scheduled-task run log (module 18, phase 2). Generated by Prisma from the
-- OpsTaskRun model, plus the header below: it is a platform table, like
-- StripeWebhookEvent, so it carries no row level security policy. marea_app
-- reaches it through the default privileges the row level security migration
-- set up; marea_worker gets nothing here on purpose.
--
-- Revert with: DROP TABLE "OpsTaskRun"; DROP TYPE "OpsTaskStatus";

-- CreateEnum
CREATE TYPE "OpsTaskStatus" AS ENUM ('RUNNING', 'SUCCEEDED', 'FAILED');

-- CreateTable
CREATE TABLE "OpsTaskRun" (
    "id" TEXT NOT NULL,
    "task" TEXT NOT NULL,
    "slot" TEXT NOT NULL,
    "status" "OpsTaskStatus" NOT NULL DEFAULT 'RUNNING',
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "processed" BIGINT,
    "detail" TEXT,

    CONSTRAINT "OpsTaskRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "OpsTaskRun_task_status_finishedAt_idx" ON "OpsTaskRun"("task", "status", "finishedAt");

-- CreateIndex
CREATE UNIQUE INDEX "OpsTaskRun_task_slot_key" ON "OpsTaskRun"("task", "slot");
