export type { Lang } from "@/lib/i18n/lang";

export const STR = {
  en: {
    nav: {
      home: "Home",
      about: "About Us",
      menu: "Our Menu",
      testimonials: "Testimonials",
      contact: "Contact",
      book: "Book a Table",
    },
    hero: {
      eyebrow: "Boutique Seafood",
      h1Before: "Seafood ",
      h1Highlight: "Delicacies",
      h1After: " That Unveil the Flavor",
      sub: "Dive into freshness — an ocean of flavors awaits at our restaurant.",
      book: "Book a Table",
      promoTitle: "Seafood from the ocean that will become your favorites",
      promoBody:
        "Fresh, delicious, and prepared with attention to detail. Come visit us and see for yourself! Place an order or reserve a table to enjoy the flavors of the sea.",
      viewMenu: "View Full Menu",
      photo: "Fresh seafood · water splash",
    },
    about: {
      eyebrow: "About Us",
    },
    stats: [
      { v: "25+", l: "Years of Experience" },
      { v: "100%", l: "Fresh Ingredients" },
      { v: "10K+", l: "Happy Customers" },
      { v: "50+", l: "Exclusive Recipes" },
    ],
    menu: {
      eyebrow: "Our Menu",
      title: "Signature plates of the season",
      lead: "Browse by course — each dish is built around the day's freshest catch.",
      book: "Book a Table",
    },
    offers: {
      eyebrow: "Exclusive Offers",
      titleBefore: "Exclusive ",
      titleHighlight: "Offers",
      titleAfter: " Just for You!",
      dish: "Signature dish",
    },
    tmls: {
      eyebrow: "Testimonials",
      title: "What our guests are saying",
      media: "Guests dining",
    },
    reserve: {
      eyebrow: "Reservation",
      title: "Reserve your table by the water",
      media: "Fresh oysters · splash",
      name: "Name",
      namePh: "Your name",
      email: "Email",
      emailPh: "you@example.com",
      phone: "Phone",
      phonePh: "+1 555 000 0000",
      contactHint: "At least one of the two",
      guests: "Number of guests",
      guest: "guest",
      guestP: "guests",
      date: "Date",
      time: "Time",
      chooseTime: "— Choose a time —",
      nextDaySuffix: " (next day)",
      loadingSlots: "Finding available times…",
      noSlotsTitle: "No availability",
      noSlotsBody: "No times are available for {n} guests on this date. Try another date or a smaller party.",
      comments: "Additional comments",
      commentsPh: "Allergies, special occasion, seating preference…",
      submit: "Reserve a table",
      submitting: "Confirming…",
      privacyNotice: "Privacy notice",
      conflictBody: "That time was just taken. Pick another available time.",
      nameRequired: "Enter your name.",
      contactRequired: "Add an email or a phone number.",
      genericError: "Something went wrong. Try again.",
      rateLimitedError: "Too many reservations from this connection recently. Try again later or call us.",
      successTitle: "Reservation confirmed!",
      successBody: "We'll see you {date} at {time} for {guests} guests.",
      confirmationCodeLabel: "Confirmation code",
      successFinePrint: "Save this code to look up or cancel your reservation.",
      copyCode: "Copy code",
      codeCopied: "Copied!",
      viewReservationLink: "View my reservation",
    },
    footer: {
      connect: "Let's connect with us",
      emailPh: "Your email address",
      subscribe: "Subscribe",
      subscribing: "Subscribing…",
      subscribeSuccess: "Check your email to confirm your subscription.",
      subscribeError: "Something went wrong. Try again.",
      invalidEmail: "Enter a valid email address.",
      privacyNotice: "Privacy notice",
      visit: "Visit Us",
      contact: "Contact",
      ourMenu: "Our Menu",
      reservations: "Reservations",
      copyright: "© 2026 Marea. All rights reserved.",
    },
  },
  es: {
    nav: {
      home: "Inicio",
      about: "Sobre Nosotros",
      menu: "Nuestro Menú",
      testimonials: "Testimonios",
      contact: "Contacto",
      book: "Reservar Mesa",
    },
    hero: {
      eyebrow: "Mariscos Boutique",
      h1Before: "",
      h1Highlight: "Delicias",
      h1After: " del Mar que Revelan el Sabor",
      sub: "Sumérgete en la frescura — un océano de sabores te espera en nuestro restaurante.",
      book: "Reservar Mesa",
      promoTitle: "Mariscos del océano que se volverán tus favoritos",
      promoBody:
        "Frescos, deliciosos y preparados con atención al detalle. ¡Ven a visitarnos y compruébalo tú mismo! Haz un pedido o reserva una mesa para disfrutar los sabores del mar.",
      viewMenu: "Ver Menú Completo",
      photo: "Mariscos frescos · salpicadura",
    },
    about: {
      eyebrow: "Sobre Nosotros",
    },
    stats: [
      { v: "25+", l: "Años de Experiencia" },
      { v: "100%", l: "Ingredientes Frescos" },
      { v: "10K+", l: "Clientes Felices" },
      { v: "50+", l: "Recetas Exclusivas" },
    ],
    menu: {
      eyebrow: "Nuestro Menú",
      title: "Platillos insignia de la temporada",
      lead: "Explora por tiempo — cada platillo se prepara con la pesca más fresca del día.",
      book: "Reservar Mesa",
    },
    offers: {
      eyebrow: "Ofertas Exclusivas",
      titleBefore: "¡",
      titleHighlight: "Ofertas",
      titleAfter: " Exclusivas Solo para Ti!",
      dish: "Platillo insignia",
    },
    tmls: {
      eyebrow: "Testimonios",
      title: "Lo que dicen nuestros comensales",
      media: "Comensales disfrutando",
    },
    reserve: {
      eyebrow: "Reservación",
      title: "Reserva tu mesa junto al mar",
      media: "Ostras frescas · salpicadura",
      name: "Nombre",
      namePh: "Tu nombre",
      email: "Correo electrónico",
      emailPh: "tucorreo@ejemplo.com",
      phone: "Teléfono",
      phonePh: "+52 55 0000 0000",
      contactHint: "Al menos uno de los dos",
      guests: "Número de personas",
      guest: "persona",
      guestP: "personas",
      date: "Fecha",
      time: "Hora",
      chooseTime: "— Elige una hora —",
      nextDaySuffix: " (día siguiente)",
      loadingSlots: "Buscando horarios disponibles…",
      noSlotsTitle: "Sin disponibilidad",
      noSlotsBody: "No hay horarios disponibles para {n} personas en esta fecha. Prueba con otra fecha o un grupo más pequeño.",
      comments: "Comentarios adicionales",
      commentsPh: "Alergias, ocasión especial, preferencia de mesa…",
      submit: "Reservar mesa",
      submitting: "Confirmando…",
      privacyNotice: "Aviso de privacidad",
      conflictBody: "Justo se ocupó ese horario. Elige otra hora disponible.",
      nameRequired: "Escribe tu nombre.",
      contactRequired: "Agrega un correo o un teléfono.",
      genericError: "Algo salió mal. Intenta de nuevo.",
      rateLimitedError: "Demasiadas reservaciones desde esta conexión hace poco. Intenta más tarde o llámanos.",
      successTitle: "¡Reserva confirmada!",
      successBody: "Te esperamos el {date} a las {time} para {guests} personas.",
      confirmationCodeLabel: "Código de confirmación",
      successFinePrint: "Guarda este código para consultar o cancelar tu reserva.",
      copyCode: "Copiar código",
      codeCopied: "¡Copiado!",
      viewReservationLink: "Ver mi reserva",
    },
    footer: {
      connect: "Conéctate con nosotros",
      emailPh: "Tu correo electrónico",
      subscribe: "Suscribirse",
      subscribing: "Suscribiendo…",
      subscribeSuccess: "Revisa tu correo para confirmar tu suscripción.",
      subscribeError: "Algo salió mal. Intenta de nuevo.",
      invalidEmail: "Ingresa un correo válido.",
      privacyNotice: "Aviso de privacidad",
      visit: "Visítanos",
      contact: "Contacto",
      ourMenu: "Nuestro Menú",
      reservations: "Reservaciones",
      copyright: "© 2026 Marea. Todos los derechos reservados.",
    },
  },
} as const;

// Categories and dishes used to live here (STR.en/es.categories/dishes) —
// they're now served from the database (lib/menu/public-menu.ts,
// fetched in app/page.tsx) so the admin panel's menu editor is the real
// source of truth. The Dish shape stays here since Dish.tsx still types
// against it.
export type Dish = {
  category: string;
  price: string;
  img: string;
  name: string;
  desc: string;
};
