-- Stripe Connect columns (module 17b, phase 2): where each payment lives, and
-- what each business's connected account can do. Generated by Prisma; the
-- guards around these columns (immutability, country format, grants for the
-- system role) are in the next migration, written by hand.
--
-- Business."stripePublishableKey" is dropped: nothing ever wrote or read it.
-- For direct charges Stripe.js takes the PLATFORM's publishable key plus the
-- connected account's id (loadStripe(key, { stripeAccount })), so no business
-- needs a key of its own.
--
-- Existing Payment rows get NULL, which is correct: they were all created on
-- the platform's account. No backfill.

-- CreateEnum
CREATE TYPE "StripeCapabilityStatus" AS ENUM ('ACTIVE', 'PENDING', 'RESTRICTED', 'UNSUPPORTED');

-- AlterTable
ALTER TABLE "Business" DROP COLUMN "stripePublishableKey",
ADD COLUMN     "stripeCardPaymentsStatus" "StripeCapabilityStatus",
ADD COLUMN     "stripeStatusCheckedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Payment" ADD COLUMN     "stripeAccountId" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX "Business_stripeAccountId_key" ON "Business"("stripeAccountId");

