-- The signup primitive (module 19, phase 2). Hand-written, like every other
-- SECURITY DEFINER function in this schema.
--
-- WHAT THIS IS. marea_app cannot create a Business (no INSERT policy exists
-- for it at all, see enable_row_level_security) or an Organization (INSERT
-- revoked outright in organization_access). A public signup form runs as
-- marea_app, so it cannot write either row on its own. marea_signup(...) is
-- the one door: it creates a brand new Organization, a Business inside it,
-- and both locale rows of BusinessTranslation, atomically, and nothing else.
-- It never receives an existing organization id — a caller cannot use it to
-- add a business to someone else's chain. Adding a branch to an existing
-- organization is a second, narrower primitive that checks the caller's own
-- business against the target organization (marea_business_org); it isn't
-- needed until the plan limits sucursales per organization (module 19,
-- phase 7), so it doesn't exist yet.
--
-- WHAT IT VALIDATES, IN THE DATABASE. The slug's shape and its reserved
-- names — the same rule as validateSlug() in lib/business-host.ts, checked
-- again here because a caller is not trusted just for having checked
-- TypeScript's copy first. lib/db/reserved-slugs.test.ts fails if the two
-- lists ever drift apart. Uniqueness is not re-checked by hand: Business.slug
-- and Organization.slug are both already UNIQUE, and this function always
-- gives them the same string, so the existing constraint is what a caller
-- sees as "slug_taken" (a unique_violation, 23505).
--
-- WHAT IT RECEIVES AND RETURNS. Six ids/strings, all generated by the
-- caller before calling (cuid2, the same generator lib/tables/actions.ts
-- already uses for a token Prisma isn't minting) — a hand-written INSERT has
-- no Prisma default to fall back on for `cuid()` columns. Returns `true`:
-- the caller already has every id it needs (RLS on Business/Organization
-- would hide the row it just inserted right back from it anyway, since the
-- connection's app.business_id still names no business at the moment this
-- runs), but `RETURNS void` does not work here — @prisma/adapter-pg cannot
-- decode a void column, and throws on the client side even though the
-- function already committed its inserts. A boolean is a native type the
-- driver decodes fine, so the caller's own try/catch stays trustworthy.
--
-- Revert with: DROP FUNCTION marea_signup(text, text, text, text, text, text);
-- ALTER TABLE "Organization" DISABLE ROW LEVEL SECURITY; DROP POLICY
-- tenant_isolation ON "Organization".

CREATE FUNCTION marea_signup(
  organization_id text,
  business_id text,
  slug text,
  name text,
  translation_id_en text,
  translation_id_es text
) RETURNS boolean
  LANGUAGE plpgsql SECURITY DEFINER SET search_path FROM CURRENT AS
$$
BEGIN
  IF slug !~ '^[a-z0-9]([a-z0-9-]{0,30}[a-z0-9])?$' THEN
    RAISE EXCEPTION 'invalid_slug: "%"', slug;
  END IF;

  -- Mirrors RESERVED_SLUGS in lib/business-host.ts exactly.
  IF slug = ANY (ARRAY[
    'www', 'admin', 'api', 'app', 'auth', 'mail', 'smtp', 'imap', 'ftp', 'static', 'assets', 'cdn', 'media',
    'status', 'docs', 'help', 'support', 'billing', 'dashboard', 'login', 'signup', 'root', 'localhost', 'test'
  ]) THEN
    RAISE EXCEPTION 'reserved_slug: "%"', slug;
  END IF;

  INSERT INTO "Organization" (id, name, slug) VALUES (organization_id, name, slug);

  -- Same shape createBusiness() in lib/tenants/provision.ts has always
  -- written: card payments start off, every other column keeps its schema
  -- default (defaultLocale 'es', supportedLocales ['en','es'], currency,
  -- timezone, taxRate...). The wizard (phase 4) is where those get set for
  -- real, not signup.
  INSERT INTO "Business" (id, slug, name, "organizationId", "acceptsOnlinePayment", "updatedAt")
    VALUES (business_id, slug, name, organization_id, false, now());

  INSERT INTO "BusinessTranslation" (id, "businessId", locale) VALUES
    (translation_id_en, business_id, 'en'),
    (translation_id_es, business_id, 'es');

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION marea_signup(text, text, text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION marea_signup(text, text, text, text, text, text) TO marea_app;

-- ---------------------------------------------------------------------------
-- Organization row level security. Not scoped when the table was created
-- (module 17, phase 4) or when organization_access revoked marea_app's write
-- access: nothing marea_app read from Organization was sensitive yet (name
-- and slug). Module 19 changes that with a per-organization subscription
-- table, and this closes the gap before that table exists rather than after,
-- the same "safety net under the filter, not a replacement for it" shape as
-- every other tenant_isolation policy in this schema. There is no query in
-- the application today that depends on reading an organization from outside
-- one of its own businesses (grep for prisma.organization. outside
-- lib/tenants/provision.ts, which always runs as the owner and so is not
-- subject to this) — the only caller inside the request path,
-- lib/auth/business-access.ts, resolves an organization's id from
-- marea_business_org(), a SECURITY DEFINER function that already runs past
-- this policy, and never selects from "Organization" directly.
-- ---------------------------------------------------------------------------
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Organization" FOR SELECT TO marea_app
  USING (id IN (SELECT organization_id FROM marea_business_org(current_setting('app.business_id', true))));
